version: '3'

services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest